### ISSUE TITLE
Garcia_GitLog screenshot

### ISSUE THREAD

**Issue by agarcia05** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-agarcia05#1]
<img width="2240" alt="Screenshot 2023-10-24 at 7 25 02 PM" src="https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-agarcia05/assets/143145609/e8000071-a6e5-4749-b1e1-94dec4a61dbd">

**Comment by instructorc** [comment]
Hi Anna - It looks like a space is needed between git and log.
